name: Chroma - Weak lensing with wavelength-dependent PSFs
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
gauges_id: 503c5af6613f5d0f19000027
repository: https://github.com/DarkEnergyScienceCollaboration/chroma
# markdown: redcarpet
markdown: kramdown
# pygments: true
baseurl: /chroma
url: /chroma